project:
  type: website
  output-dir: docs

website:
  title: "Sakar Dahal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobbies.qmd
        text: Hobbies

format:
  html:
    theme: vapor